---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/2 17:07
---

antiairList = {}

local outputFileName = "·À¿ÕÅÚFromScripts.csv"


local D_EDT = pg.equip_data_template
local D_EDS = pg.equip_data_statistics
local D_WP = pg.weapon_property
--local D_BA_T = pg.barrage_template
--local D_BU_T = pg.bullet_template
local D_EDBT = pg.equip_data_by_type


local function genAntiairList()
    for key, value in pairs(D_EDT) do
        if value and type(key) == "number" and not value.base then
            compare_group = D_EDBT[value.type].compare_group
            if compare_group == EquipTypeEnum["Antiair"] then
                --antiairList[key] = {}
                table.insert(antiairList, key, {})
            end
        end
    end
end

local function collectAntiairData()
    for k, v in pairs(antiairList) do
        if EquipRarityName[D_EDS[k].rarity] ~= "Gray" then
            v["icon"] = D_EDS[k].icon
            v["name"] = D_EDS[k].name
            v["tech"] = D_EDS[k].tech
            v["rarity"] = D_EDS[k].rarity
            v["max_lv"] = getEquipMaxLv(k)
            v["damage"] = D_WP[k].damage
            v["up_damage"] = getWeaponProp(k, v.max_lv, "damage")
            v["reload_max"] = D_WP[k].reload_max
            v["up_reload_max"] = getWeaponProp(k, v.max_lv, "reload_max")
            v["range"] = D_WP[k].range
            v["value_2"] = D_EDS[k].value_2  --antiaircraft
            if D_EDS[k].attribute_2 then
                v[D_EDS[k].attribute_2] = D_EDS[k].value_2
            end
            if D_EDS[k].attribute_3 then --hit or cannon
                v[D_EDS[k].attribute_3] = D_EDS[k].value_3
            end
            v["corrected"] = D_WP[k].corrected
            v["up_corrected"] = getWeaponProp(k, v.max_lv, "corrected")
            if v.max_lv > 10 then
                v["corrected_10"] = getWeaponProp(k, 10, "corrected")
            end
            v["nationality"] = D_EDS[k].nationality
        end
    end
end

local antiairHeaderString = "icon,name,rarity,max_lv,damage,up_damage,reload_time,up_reload_time,range,antiair,accuracy,cannon,corrected,up_corrected,nationality"
local function antiairToString(e, is_half_up)
    name = e.name .. "T" .. e.tech
    res = e.icon
    res = res .. "," .. name
    if is_half_up then
        res = res .. "_up10"
    end
    res = res .. "," .. EquipRarityName[e.rarity]
    res = res .. "," .. e.max_lv
    res = res .. "," .. e.damage
    res = res .. "," .. e.up_damage
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(e.reload_max))
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(e.up_reload_max))
    res = res .. "," .. e.range

    res = res .. "," .. ((e["antiaircraft"] and tostring(e["antiaircraft"])) or "0")
    res = res .. "," .. ((e["hit"] and tostring(e["hit"])) or "0")
    res = res .. "," .. ((e["cannon"] and tostring(e["cannon"])) or "0")
    res = res .. "," .. e.corrected
    if is_half_up then
        res = res .. "," .. e.corrected_10
    else
        res = res .. "," .. e.up_corrected
    end
    res = res .. "," .. ((e.nationality and NationalityName[e.nationality]) or "")

    return res
end

local function writeAntiairsToFile()
    local file = io.open (outputFileName, "w")

    file:write(antiairHeaderString.."\n")

    for k, v in pairs(antiairList) do
        if EquipRarityName[D_EDS[k].rarity] ~= "Gray" then
            local str = antiairToString(v, false)
            file:write(str .."\n")
            if v.max_lv > 10 then
                str = antiairToString(v, true)
                file:write(str .."\n")
            end
        end
    end

    file:close()
end

function exportAntiairs()
    genAntiairList()
    collectAntiairData()
    writeAntiairsToFile()
end
