---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/2 17:07
---

antiairList = {}

local outputFileName = "防空炮FromScripts.csv"



local D_EDT = pg.equip_data_template
local D_EDS = pg.equip_data_statistics
local D_WP = pg.weapon_property
local D_BA_T = pg.barrage_template
local D_BU_T = pg.bullet_template
local D_EDBT = pg.equip_data_by_type


local function getBarrageProp(barrageNo, propName)
    return D_BA_T[barrageNo][propName]
end

local function getBulletProp(bulletNo, propName)
    return D_BU_T[bulletNo][propName]
end

function CalculateReloadTime(reload_max, reload)
    if reload == nil then
        reload = BattleConfig.K2
    end
    return reload_max / BattleConfig.K1 / math.sqrt((reload + BattleConfig.K2) * BattleConfig.K3)
end

local function calculateBulletNum(antiair)
    return (antiair.primal_repeat + 1) * (antiair.senior_repeat + 1)
end

local function genAntiairList()
    for key, value in pairs(D_EDT) do
        if value and type(key) == "number" and not value.base then
            compare_group = D_EDBT[value.type].compare_group
            if compare_group == EquipTypeEnum["Antiair"] then
                --antiairList[key] = {}
                table.insert(antiairList, key, {})
            end
        end
    end
end

local function collectAntiairData()
    for k, v in pairs(antiairList) do
        v["icon"] = D_EDS[k].icon
        v["name"] = D_EDS[k].name
        v["tech"] = D_EDS[k].tech
        v["rarity"] = D_EDS[k].rarity
        v["type"] = D_EDS[k].type
        v["max_lv"] = getEquipMaxLv(k)
        v["damage"] = D_WP[k].damage
        v["up_damage"] = getWeaponProp(k, v.max_lv, "damage")
        v["primal_repeat"] = getBarrageProp(D_WP[k].barrage_ID[1], "primal_repeat")
        v["senior_repeat"] = getBarrageProp(D_WP[k].barrage_ID[1], "senior_repeat")
        v["senior_delay"] = getBarrageProp(D_WP[k].barrage_ID[1], "senior_delay")
        v["reload_max"] = D_WP[k].reload_max
        v["up_reload_max"] = getWeaponProp(k, v.max_lv, "reload_max")
        v["range"] = getBulletProp(D_WP[k].bullet_ID[1], "range")
        v["spread"] = getBarrageProp(D_WP[k].barrage_ID[1], "angle")
        v["value_2"] = D_EDS[k].value_2  --antiair
        v["attribute_2"] = D_EDS[k].attribute_2
        v["value_3"] = D_EDS[k].value_3  --antiAircraft
        v["attribute_3"] = D_EDS[k].attribute_3
        v["aim_type"] = D_WP[k].aim_type
        v["angle"] = D_WP[k].angle
        v["ammo_type"] = getBulletProp(D_WP[k].bullet_ID[1], "ammo_type")
        v["damage_type"] = getBulletProp(D_WP[k].bullet_ID[1], "damage_type") --护甲补正，三元table
        v["corrected"] = D_WP[k].corrected
        v["up_corrected"] = getWeaponProp(k, v.max_lv, "corrected")
        v["nationality"] = D_EDS[k].nationality
        v["speciality"] = D_EDS[k].speciality
    end
end

local antiairHeaderString = "icon,name,rarity,type,max_lv,damage,up_damage,bullet_num,reload_time,up_reload_time,range,spread,antiair,antiair,speciality,angle,ammo_type,corrected,up_corrected,senior_delay,vs轻,vs中,vs重"
local function antiairToString(c)
    name = c.name .. "T" .. c.tech
    res = c.icon
    res = res .. "," .. name
    res = res .. "," .. EquipRarityName[c.rarity]
    res = res .. "," .. EquipType.Type2Name2(c.type)
    res = res .. "," .. c.max_lv
    res = res .. "," .. c.damage
    res = res .. "," .. c.up_damage
    res = res .. "," .. calculateBulletNum(c)
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(c.reload_max))
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(c.up_reload_max))
    res = res .. "," .. c.range
    res = res .. "," .. calculateSpread(c)
    res = res .. "," .. c.value_2
    res = res .. "," .. c.value_3
    res = res .. "," .. c.speciality
    res = res .. "," .. c.angle
    res = res .. "," .. AmmoTypeName[c.ammo_type]
    res = res .. "," .. c.corrected
    res = res .. "," .. c.up_corrected
    res = res .. "," .. (c.senior_delay * c.senior_repeat)
    res = res .. "," .. c.damage_type[1]
    res = res .. "," .. c.damage_type[2]
    res = res .. "," .. c.damage_type[3]

    return res
end

local function writeAntiairsToFile()
    local file = io.open (outputFileName, "w")

    file:write(antiairHeaderString.."\n")

    for k, v in pairs(antiairList) do
        local str = antiairToString(v)
        file:write(str .."\n")
    end

    file:close()
end

function exportAntiairs()
    genAntiairList()
    collectAntiairData()
    writeAntiairsToFile()
end
