---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/16 21:22
---

Cannons = {}

local inputFileName = "舰炮.csv"
local outputFileName = "舰炮Complete.csv"

--注意，需要把相关statistics文件转成GBK格式！！！
require("CN.sharecfg.weapon_property")
require("CN.sharecfg.equip_data_statistics")
require("CN.sharecfg.barrage_template")
require("CN.sharecfg.bullet_template")
local D_EDS = pg.equip_data_statistics
local D_WP = pg.weapon_property
local D_BA_T = pg.barrage_template
local D_BU_T = pg.bullet_template

local D_EDS_INDEX = {}
local function createIndexByName()
    D_EDS_INDEX = {}
    for k, v in pairs(D_EDS) do
        if k and type(k) == "number" and k % 10 == 0 and v and v.base == nil then
            local name = D_EDS[k].name.."T"..D_EDS[k].tech
            if D_EDS[k].name == "120mm单装炮" then
                if D_EDS[k].nationality == 2 then
                    name = name.."（皇家）"
                elseif D_EDS[k].nationality == 3 then
                    name = name.."（重樱）"
                end
            elseif D_EDS[k].name == "三联装152mm主炮" and D_EDS[k].tech == 1 then
                if D_EDS[k].nationality == 2 then
                    name = name.."（皇家）"
                end
            end
            if D_EDS[k].rarity >= 4 then
                D_EDS_INDEX[name] = D_EDS[k+10]
            elseif D_EDS[k].rarity == 3 then
                D_EDS_INDEX[name] = D_EDS[k+6]
            elseif D_EDS[k].rarity <= 2 then
                D_EDS_INDEX[name] = D_EDS[k+3]
            end
        end
    end
end

local function loadCannons()
    local csv = require"csv"
    local f = csv.open(inputFileName, {header = true})
    for fields in f:lines() do
        local name = ""
        for k, v in pairs(fields) do
            if k == "name" then
                name = v
            end
        end
        Cannons[name] = {}
        for k, v in pairs(fields) do
            Cannons[name][k] = v
        end
        print(name)

        wp_id = D_EDS_INDEX[name].base
        ba_t_id = D_WP[wp_id].barrage_ID[1]
        bu_t_id = D_WP[wp_id].bullet_ID[1]

        Cannons[name]["corrected"] = D_WP[wp_id].corrected
        Cannons[name]["senior_delay"] = D_BA_T[ba_t_id].senior_delay * D_BA_T[ba_t_id].senior_repeat
        Cannons[name]["vs_light"] = D_BU_T[bu_t_id].damage_type[1]
        Cannons[name]["vs_mid"] = D_BU_T[bu_t_id].damage_type[2]
        Cannons[name]["vs_heavy"] = D_BU_T[bu_t_id].damage_type[3]
    end
end

local function writeCannonToStr(c)
    local str = c.name .. "," .. c.color .. "," .. c.shipType .. "," .. c.damage .. "," .. c.upDamage .. "," .. c.round .. ","
            .. c.speed .. "," .. c.upSpeed .. "," .. c.range .. "," .. c.spread .. "," .. c.cannon .. "," .. c.antiair .. ","
            .. c.trajectory .. "," .. c.angle .. "," .. c.ammoType .. "," .. c.box .. "," .. c.drop .. "," .. c.icon .. ","
            .. c.corrected .. "," .. c.senior_delay .. "," .. c.vs_light .. "," .. c.vs_mid .. "," .. c.vs_heavy
    return str
end

local function writeCannonsToFile()
    local file = io.open (outputFileName, "w")
    local header="name,color,shipType,damage,upgradeDamage,damageRound,speed,upgradeSpeed,range,spread,cannon,antiair,"..
            "trajectory,angle,ammoType,box,drop,icon,corrected,senior_delay,vs_light,vs_mid,vs_heavy"

    file:write(header.."\n")

    for k, v in pairs(Cannons) do
        local str = writeCannonToStr(v)
        file:write(str.."\n")
    end

    file:close()
end

function completeCannonsInfo()
    createIndexByName()
    loadCannons();
    writeCannonsToFile();
end