---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/3 2:46
---

--from "CN.mod.battle.data.battleconst"
EquipmentType = {
    MAIN_CANNON = 1,
    SUB_CANNON = 2,
    TORPEDO = 3,
    ANTI_AIR = 4,
    ARMOR = 5,
    ENGINE = 6,
    RADAR = 7,
    PASSIVE_SCOUT = 10,
    SCOUT = 11,
    CREW = 12,
    CHARGE = 13,
    SPECIAL = 14,
    MEGA_CHARGE = 15,
    MANUAL_TORPEDO = 16,
    ANTI_SEA = 17,
    HAMMER_HEAD = 18,
    BOMBER_PRE_CAST_ALERT = 19,
    MULTI_LOCK = 20,
    MANUAL_SUB = 21,
    FLEET_ANTI_AIR = 22,
    POINT_HIT_AND_LOCK = 23,
    BEAM = 24,
    DEPTH_CHARGE = 25,
    REPEATER_ANTI_AIR = 26,
    MANUAL_AAMISSILE = 28,
    DISPOSABLE_TORPEDO = 27,
    SPACE_LASER = 28,
    MISSILE = 29,
    PREVIEW_ARICRAFT = 99,
    AIR_ASSIST = "airAssist"
}