---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/1/21 15:35
---

-- drawCardExpectation just loop
--[[
function drawCardExpectation()
    local pCards = {0.02, 0.025, 0.025, 0.05}
    local len = #pCards

    local e1 = 0
    for i = 1, len do
        e1 = e1 + 1 / pCards[i]
    end

    local e2 = 0
    for i = 1, len - 1 do
        for j = i + 1, len do
            e2 = e2 + 1 / (pCards[i] + pCards[j])
        end
    end

    local e3 = 0
    for i = 1, len - 2 do
        for j = i + 1, len - 1 do
            for k = j + 1, len do
                e3 = e3 + 1 / (pCards[i] + pCards[j] + pCards[k])
            end
        end
    end

    local e4 = 0
    for i = 1, len - 3 do
        for j = i + 1, len - 2 do
            for k = j + 1, len - 1 do
                for l = k + 1, len do
                    e4 = e4 + 1 / (pCards[i] + pCards[j] + pCards[k] + pCards[l])
                end
            end
        end
    end

    print(e1 - e2 + e3 - e4)

end
]]--

function polySum(probs, indexes)
    local sum = 0
    local len = #probs
    local index_count = #indexes
    if indexes[index_count] <= len then
        local sum1 = 0
        for i = 1, index_count - 1 do
            sum1 = sum1 + probs[indexes[i]]
        end
        for j = indexes[index_count], len do
            sum = sum + 1 / (sum1 + probs[j])
        end
        indexes[index_count] = len
    end
    for i = index_count, 1, -1 do
        if indexes[i] < len + i - index_count then
            indexes[i] = indexes[i] + 1
            for j = i + 1, index_count do
                indexes[j] = indexes[j - 1] + 1
            end
            sum = sum + polySum(probs, indexes)
        end
    end
    return sum
end

function polySumN(probs, n)
    local indexes = {}
    for i = 1, n do
        indexes[i] = i
    end
    return polySum(probs, indexes)
end

function drawCardExpectation(pCards)
    local len = #pCards
    local res = 0
    for i = 1, len do
        if i % 2 == 1 then
            res = res + polySumN(pCards, i)
        else
            res = res - polySumN(pCards, i)
        end
    end
    return res
end

-- local pCards = {0.02, 0.02, 0.015, 0.025, 0.025} --北方联合活动
local pCards = {0.02, 0.025, 0.025, 0.05} --闹腾嬉戏东煌春节
print(drawCardExpectation(pCards))


