---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/2 17:07
---

CannonsFromScripts = {}
EquipTypeEnum = {  -- compare_group in D_EDBT
    ["Cannon"] = 1,
    ["Torpedo"] = 2,
    ["Antiair"] = 3,
    ["plane"] = 4,
    ["facility"] = 5,
    ["Torpedo_SM"] = 6,
}

EquipTypeName= {  -- compare_group in D_EDBT
    [1] = "Cannon",
    [2] = "Torpedo",
    [3] = "Antiair",
    [4] = "plane",
    [5] = "facility",
    [6] = "Torpedo_SM",
}


EquipRarityEnum = {  -- rarity in D_EDS
    ["Gray"] = 2,
    ["Blue"] = 3,
    ["Purple"] = 4,
    ["Gold"] = 5,
    ["SSR"] = 6,
}

EquipRarityName = {  -- rarity in D_EDS
    [2] = "Gray",
    [3] = "Blue",
    [4] = "Purple",
    [5] = "Gold",
    [6] = "SSR",
}


EquipTypeName = {  -- type in D_EDS, equip_type in D_EDBT
    [1] = "舰炮(驱逐)",
    [2] = "舰炮(轻巡)",
    [3] = "舰炮(重巡)",
    [4] = "舰炮(战列)",
    [5] = "鱼雷",
    [6] = "防空炮",
    [7] = "战斗机",
    [8] = "鱼雷机",
    [9] = "轰炸机",
    [10] = "设备",
    [11] = "舰炮(大口径重巡)",
    [12] = "水上机",
    [13] = "鱼雷(潜艇)",
    [14] = "设备",
    [15] = "反潜机",
    [17] = "直升机",
    [18] = "货物",
}


local outputFileName = "舰炮FromScripts.csv"


--[[
require("CN.sharecfg.equip_data_template")
require("CN.sharecfg.equip_data_statistics")
require("CN.sharecfg.weapon_property")
require("CN.sharecfg.barrage_template")
require("CN.sharecfg.bullet_template") --]]

local D_EDT = pg.equip_data_template
local D_EDS = pg.equip_data_statistics
local D_WP = pg.weapon_property
local D_BA_T = pg.barrage_template
local D_BU_T = pg.bullet_template
local D_EDBT = pg.equip_data_by_type


local function getEquipMaxLv(key)
    local tmp = key
    while(D_EDT[tmp + 1]) do
        tmp = tmp + 1
    end
    return tmp - key
end

local function getWeaponProp(equipNo, lv, propName)
    return D_WP[equipNo][equipNo + lv][propName]
end

local function getBarrageProp(barrageNo, propName)
    return D_BA_T[barrageNo][propName]
end

local function getBulletProp(bulletNo, propName)
    return D_BU_T[bulletNo][propName]
end

cannonList = {}
function genCannonList()
    for key, value in pairs(D_EDT) do
        if value and type(key) == "number" and not value.base then
            compare_group = D_EDBT[value.type].compare_group
            if compare_group == EquipTypeEnum["Cannon"] then
                --cannonList[key] = {}
                table.insert(cannonList, key, {})
            end
        end
    end
end

function collectCannonData()
    for k, v in pairs(cannonList) do
        v["name"] = D_WP[k].name
        v["rarity"] = D_EDS[k].rarity
        v["type"] = D_EDS[k].type
        v["damage"] = D_WP[k].damage
        v["lvLimit"] = getEquipMaxLv(k)
        v["up_damage"] = getWeaponProp(k, v.lvLimit, "damage")
        v["primal_repeat"] = getBarrageProp(D_WP[k].barrage_ID[1], "primal_repeat")
        v["senior_repeat"] = getBarrageProp(D_WP[k].barrage_ID[1], "senior_repeat")
        v["senior_delay"] = getBarrageProp(D_WP[k].barrage_ID[1], "senior_delay")
        v["reload_max"] = D_WP[k].reload_max
        v["up_reload_max"] = getWeaponProp(k, v.lvLimit, "reload_max")
        v["range"] = D_WP[k].range
        v["spread"] = getBarrageProp(D_WP[k].barrage_ID[1], "angle")
        v["value_2"] = D_EDS[k].value_2  --cannon
        v["attribute_2"] = D_EDS[k].attribute_2
        v["value_3"] = D_EDS[k].value_3  --antiAircraft
        v["attribute_3"] = D_EDS[k].attribute_3
        v["aim_type"] = D_WP[k].aim_type
        v["angle"] = D_WP[k].angle
        v["ammo_type"] = getBulletProp(D_WP[k].bullet_ID[1], "ammo_type")
        v["damage_type"] = getBulletProp(D_WP[k].bullet_ID[1], "damage_type") --护甲补正，三元table
        v["corrected"] = D_WP[k].corrected
        v["nationality"] = D_EDS[k].nationality
        v["speciality"] = D_EDS[k].speciality
    end
end


function eeTest()
    genCannonList()
    --print(#cannonList)
    --print(convert_table_to_string(cannonList))

    collectCannonData()

    --[[local D_WP = pg.weapon_property
    count = 0
    for key, value in pairs(cannonList) do
        if D_WP[value] and D_WP[value].name then
            print(value .. ", " .. D_WP[value].name .. ", " .. getEquipMaxLv(value))
            count = count + 1
        end
    end
    print(count)]]--

    count = 0
    for key, value in pairs(cannonList) do
        print(key .. ", " .. value.name .. ", " .. EquipRarityName[value.rarity] .. ", " .. getEquipMaxLv(key))
        count = count + 1
    end
    print(count)

end
