---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/2 17:07
---

EquipTypeEnum = {  -- compare_group in D_EDBT
    ["Cannon"] = 1,
    ["Torpedo"] = 2,
    ["Antiair"] = 3,
    ["plane"] = 4,
    ["facility"] = 5,
    ["Torpedo_SM"] = 6,
}

EquipTypeName= {  -- compare_group in D_EDBT
    [1] = "Cannon",
    [2] = "Torpedo",
    [3] = "Antiair",
    [4] = "plane",
    [5] = "facility",
    [6] = "Torpedo_SM",
}


EquipRarityEnum = {  -- rarity in D_EDS
    ["Gray"] = 2,
    ["Blue"] = 3,
    ["Purple"] = 4,
    ["Gold"] = 5,
    ["SSR"] = 6,
}

EquipRarityName = {  -- rarity in D_EDS
    [1] = "Gray",
    [2] = "Gray",
    [3] = "Blue",
    [4] = "Purple",
    [5] = "Gold",
    [6] = "SSR",
}

EquipTypeName = {  -- type in D_EDS, equip_type in D_EDBT
    [1] = "舰炮(驱逐)",
    [2] = "舰炮(轻巡)",
    [3] = "舰炮(重巡)",
    [4] = "舰炮(战列)",
    [5] = "鱼雷",
    [6] = "防空炮",
    [7] = "战斗机",
    [8] = "鱼雷机",
    [9] = "轰炸机",
    [10] = "设备",
    [11] = "舰炮(大口径重巡)",
    [12] = "水上机",
    [13] = "鱼雷(潜艇)",
    [14] = "设备",
    [15] = "反潜机",
    [17] = "直升机",
    [18] = "货物",
}


NationalityName = {  -- nationality in D_WP
    [1] = "白鹰",
    [2] = "皇家",
    [3] = "重樱",
    [4] = "铁血",
    [5] = "Unknown",
    [6] = "撒丁帝国",
    [7] = "北方联合",
    [8] = "自由鸢尾",
}



local D_EDT = pg.equip_data_template
local D_WP = pg.weapon_property
local D_BA_T = pg.barrage_template
local D_BU_T = pg.bullet_template

function getEquipMaxLv(key)
    local tmp = key
    while(D_EDT[tmp].next ~= 0) do
        tmp = tmp + 1
    end
    return tmp - key
end

function getEquipHalfLv(key)
    return math.min(10, getEquipMaxLv(key))
end

function getWeaponProp(equipNo, lv, propName)
    --print("#DEBUG#: " .. equipNo .. " " .. lv .. " " .. propName)
    local upProp = D_WP[equipNo + lv][propName]
    if upProp ~= nil then
        return upProp
    else
        return D_WP[equipNo][propName]
    end
end

function getBarrageProp(barrageNo, propName)
    return D_BA_T[barrageNo][propName]
end

function getBulletProp(bulletNo, propName)
    return D_BU_T[bulletNo][propName]
end

function CalculateReloadTime(reload_max, reload)
    if reload == nil then
        reload = BattleConfig.K2
    end
    return reload_max / BattleConfig.K1 / math.sqrt((reload + BattleConfig.K2) * BattleConfig.K3)
end

require("cannonExport")
require("antiairExport")
require("aircraftExport")

function equipExport()
    -- exportCannons()
    -- exportAntiairs()
    exportAircrafts()
end
