---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/1/7 20:59
---

ys = {}
pg = {
    _weak = setmetatable({}, {
        __mode = "k"
    })
}

--require("CN.include")
require("includeCopy")


local startTime = os.clock()
print("Start!")


require("equipExport")
equipExport()


local endTime = os.clock()
print("finished!")
print("total time = "..endTime - startTime)




