---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/2 17:07
---

torpedoList = {}

local outputFileName = "鱼雷FromScripts.csv"


local D_EDT = pg.equip_data_template
local D_EDS = pg.equip_data_statistics
local D_WP = pg.weapon_property
local D_BA_T = pg.barrage_template
local D_BU_T = pg.bullet_template
local D_EDBT = pg.equip_data_by_type


local function calculateBulletNum(torpedo)
    return (torpedo.primal_repeat + 1) * (torpedo.senior_repeat + 1)
end

local function calculateSpread(c)
    if c.spread < 0 then
        return -2 * c.spread
    else
        return c.spread
    end
end

local function genTorpedoList()
    for key, value in pairs(D_EDT) do
        if value and type(key) == "number" and not value.base then
            compare_group = D_EDBT[value.type].compare_group
            if compare_group == EquipTypeEnum["Torpedo"] or compare_group == EquipTypeEnum["Torpedo_SM"] then
                --torpedoList[key] = {}
                table.insert(torpedoList, key, {})
            end
        end
    end
end

local function collectTorpedoData()
    for k, v in pairs(torpedoList) do
        v["icon"] = D_EDS[k].icon
        v["name"] = D_EDS[k].name
        v["tech"] = D_EDS[k].tech
        v["rarity"] = D_EDS[k].rarity
        v["type"] = D_EDS[k].type
        v["max_lv"] = getEquipMaxLv(k)
        v["damage"] = D_WP[k].damage
        v["up_damage"] = getWeaponProp(k, v.max_lv, "damage")
        v["num"] = 0
        for _, b in pairs(D_WP[k].barrage_ID) do
            v["num"] = v["num"] + D_BA_T[b].primal_repeat + 1
        end
        v["reload_max"] = D_WP[k].reload_max
        v["up_reload_max"] = getWeaponProp(k, v.max_lv, "reload_max")
        v["value_2"] = D_EDS[k].value_2  --torpedo
        v["attribute_2"] = D_EDS[k].attribute_2

        local bullet = D_BU_T[D_WP[k].bullet_ID[1]]
        local barrage = D_BA_T[D_WP[k].barrage_ID[1]]
        v["spread"] = barrage.delta_angle * barrage.primal_repeat - barrage.angle
        v["aim_angle"] = D_WP[k].angle
        v["aim_range"] = D_WP[k].range
        v["range_offset"] = bullet.range_offset
        v["range"] = bullet.range
        v["velocity"] = bullet.velocity
        if bullet.acceleration["tracker"] then
            v["ammo_type"] = "声导"
        else
            v["ammo_type"] = "通常"
        end
        v["damage_type"] = getBulletProp(D_WP[k].bullet_ID[1], "damage_type") --护甲补正，三元table
        v["corrected"] = D_WP[k].corrected
        v["up_corrected"] = getWeaponProp(k, v.max_lv, "corrected")
            if v.max_lv > 10 then
                v["corrected_10"] = getWeaponProp(k, 10, "corrected")
            end
        v["nationality"] = D_EDS[k].nationality
        v["speciality"] = D_EDS[k].speciality
    end
end

local torpedoHeaderString = "icon,name,rarity,shipType,max_lv,damage,up_damage,num,reload_time,up_reload_time,torpedo,spread,aim_angle,aim_range,range_offset,range,velocity,ammo_type,corrected,up_corrected,vs轻,vs中,vs重,nationality"
local function torpedoToString(e, is_half_up)
    name = e.name .. "T" .. e.tech
    res = e.icon
    res = res .. "," .. name
    if is_half_up then
        res = res .. "_up10"
    end
    res = res .. "," .. EquipRarityName[e.rarity]
    res = res .. "," .. EquipType.Type2Name2(e.type)
    res = res .. "," .. e.max_lv
    -- res = res .. "," .. tostring(is_half_up)
    res = res .. "," .. e.damage
    res = res .. "," .. e.up_damage
    res = res .. "," .. e.num
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(e.reload_max))
    res = res .. "," .. string.format("%0.2f", CalculateReloadTime(e.up_reload_max))
    res = res .. "," .. e.value_2
    res = res .. "," .. e.spread
    res = res .. "," .. e.aim_angle
    res = res .. "," .. e.aim_range
    res = res .. "," .. e.range_offset
    res = res .. "," .. e.range
    res = res .. "," .. e.velocity
    res = res .. "," .. e.ammo_type
    res = res .. "," .. e.corrected
    if is_half_up then
        res = res .. "," .. e.corrected_10
    else
        res = res .. "," .. e.up_corrected
    end
    res = res .. "," .. e.damage_type[1]
    res = res .. "," .. e.damage_type[2]
    res = res .. "," .. e.damage_type[3]
    res = res .. "," .. ((e.nationality and NationalityName[e.nationality]) or "")

    return res
end

local function writeTorpedosToFile()
    local file = io.open (outputFileName, "w")

    file:write(torpedoHeaderString.."\n")

    for k, v in pairs(torpedoList) do
        if EquipRarityName[D_EDS[k].rarity] ~= "Gray" then
            local str = torpedoToString(v, false)
            file:write(str .."\n")
            if v.max_lv > 10 then
                str = torpedoToString(v, true)
                file:write(str .."\n")
            end
        end
    end

    file:close()
end

function exportTorpedos()
    genTorpedoList()
    collectTorpedoData()
    writeTorpedosToFile()
end
