---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/1/3 1:21
---




-- 序列化tablle表--將表轉化成string
function ut_serialize(obj)
    local lua = ""
    local t = type(obj)
    if t == "number" then
        lua = lua .. obj
    elseif t == "boolean" then
        lua = lua .. tostring(obj)
    elseif t == "string" then
        lua = lua .. string.format("%q", obj)
    elseif t == "table" then
        lua = lua .. "{\n"
        for k, v in pairs(obj) do
            lua = lua .. "[" .. ut_serialize(k) .. "]=" .. ut_serialize(v) .. ",\n"
        end
        local metatable = getmetatable(obj)
        if metatable ~= nil and type(metatable.__index) == "table" then
            for k, v in pairs(metatable.__index) do
                lua = lua .. "[" .. ut_serialize(k) .. "]=" .. ut_serialize(v) .. ",\n"
            end
        end
        lua = lua .. "}"
    elseif t == "nil" then
        return nil
    else
        return "-nil-"
        --error("can not serialize a " .. t .. " type.")
    end
    return lua
end

-- 反序列化tablle表--將string轉化成table
function ut_unserialize(lua)
    local t = type(lua)
    if t == "nil" or lua == "" then
        return nil
    elseif t == "number" or t == "string" or t == "boolean" then
        lua = tostring(lua)
    else
        error("can not unserialize a " .. t .. " type.")
    end
    lua = "return " .. lua
    local func = loadstring(lua)
    if func == nil then
        return nil
    end
    return func()
end

-- 一次性加载所有表格
--[[
local lfs = require "lfs"
dataPath = "sharecfg"
for file in lfs.dir(dataPath) do
    if file~='.' and file~='..' then
        local filename = string.gsub(file, ".lua$", "")
        if ShareCfg["ShareCfg." .. filename] and filename ~= "gameset_language_client" and filename ~= "word_legal_template" and filename ~= "word_template" then
            local loadf = dataPath..'/'..filename
            require(loadf)
        end
    end
end
]]--

--print(ut_serialize(pg.activity_7_day_sign))


function match_table(t1, t2)
    for i = 1, #t1 do
        if t1[i] ~= t2[i] then
            return false
        end
    end
    return true
end


function convert_table_to_string(t)
    local str = ""
    local len = #t
    local first = true
    for i = 1, len do
        if first then
            str = t[i]
            first = false
        else
            str = str..","..t[i]
        end
    end
    return str
end
